### ISSUE TITLE
ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon.

### ISSUE THREAD

**Issue by wimsymons** [novotnyr/maven-version-idea-plugin#6]
Hi,

I'm getting this error in the latest IntelliJ IDEA (2024.1.1):

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.novotnyr.mavenversion.ToggleShowMavenSettingsAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.novotnyr.maven-version-idea-plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:200)
```

Kind regards

Wim

**Comment by novotnyr** [comment]
Fixed via abd0fe76db7f99584e0603fa13aa3a6f8f69b299
